[build]
  command = "npm run generate-posts-json && npm run generate-projects && npm run generate-jobs && npm run build"
  publish = "build"

[[redirects]]
  from = "http://willkeck.com/*"
  to = "https://www.willkeck.com/:splat"
  status = 301
  force = true