# admin/config.yml
backend:
  name: github
  repo: github.com/GuillaumeGateau/my-portfolio
  branch: main # Or master, or any branch you use

media_folder: "public/images/uploads" # Folder where uploaded images will be stored
public_folder: "/images/uploads"       # Public URL for uploaded images

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }

# Add the following section to trigger the build hook after publishing
# events:
#  afterPublish: "https://api.netlify.com/build_hooks/your-build-hook-id"